### ISSUE TITLE
edge cases in scm_locate function within scm-index

### ISSUE THREAD

**Issue by kcherr1** [rlk/scm#6]
Within the scm_locate function in module, scm-index, there exists edge cases where some values of vector *v* will not cause an assignment to face *a*. As an example, if *v* = {0.6262187,  -0.4644354,   0.6262187}, none of the if conditions are true, and *a* remains unassigned.

**Comment by rlk** [comment]
Fixed by 986c6fe95e4e654a517ac4361b417b520b26cd0c.

While I wish there were a standard approach to handle this condition, the GL spec states "If two
or more coordinates have the identical magnitude, the implementation may define the rule to disambiguate this situation." So, by changing less-than comparisons to less-or-equal, lower numbered pages are favored.
